### ISSUE TITLE
Make Interference model working

### ISSUE THREAD

**Issue by kurianbenoy** [ManishSoni1908/Mobilenet-ssd-keras#2]
- currently, you have given your `file location` in [file](https://github.com/ManishSoni1908/Mobilenet-ssd-keras/blob/master/inference/infer_mobilenet_ssd.py). Make it usable for everyone like <Your Folder name path>
- Is cuda necessary for this?
> https://github.com/ManishSoni1908/Mobilenet-ssd-keras/blob/master/inference/infer_mobilenet_ssd.py#L16
(do confirm)
- There is an import error coming
```Using TensorFlow backend.
Traceback (most recent call last):
  File "infer_mobilenet_ssd.py", line 4, in <module>
    from models.ssd_mobilenet import ssd_300
  File "/home/kurian/Projects/internship/Mobilenet-ssd-keras/models/ssd_mobilenet.py", line 12, in <module>
    from models.mobilenet_v1 import mobilenet
  File "/home/kurian/Projects/internship/Mobilenet-ssd-keras/models/mobilenet_v1.py", line 8, in <module>
    from depthwise_conv2d import DepthwiseConvolution2D
ImportError: No module named 'depthwise_conv2d'
```

I can help with a PR if you want @ManishSoni1908 because I am also tinkering on the same thing right now. Can you check why the import error is coming?

**Comment by abhinavrai44** [comment]
It's an import error.. The file is present in the models folder
