### ISSUE TITLE
Mismatched shape. I think I'm missing a step.

### ISSUE THREAD

**Issue by kenthinson** [ManishSoni1908/Mobilenet-ssd-keras#7]
Hello. Thanks for making this great program. I've been able to get it working on my machine and I was able to train with a different dataset. However when I try to use infer_mobilenet_ssd.py  I get this error. 
```
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 8. Shapes are [1,1,512,6] and [8,512,1,1]. for 'Assign_175' (op: 'Assign') with input shapes: [1,1,512,6], [8,512,1,1].
```
I'm guessing I'm missing something. I'm only training with 1 class. If you can point out where I'm going wrong that would be a great help. I tried googling the error and didn't find any answer that seemed to help me understand what I'm doing wrong. Thanks!

**Comment by SanthoshRajendiran** [comment]
This has something to do with the h5py. It is not saving the model properly and it is still an open issue. Looking out for ways to address the same.

**Comment by davideCremona** [comment]
I'm having the same type of issue when I try to load the model saved during training for evaluation. This is the error:
`ValueError: Dimension 0 in both shapes must be equal, but are 1 and 84. Shapes are [1,1,512,63] and [84,512,1,1]. for 'Assign_175' (op: 'Assign') with input shapes: [1,1,512,63], [84,512,1,1].`

Please @kenthinson  help if you solved this.
